fix lint action when no lint errors

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,7 +45,7 @@ jobs:
 
       - name: Run ESLint
         run: |
-          npx eslint '{src,apps,libs,test}/**/*.ts' --format json --output-file eslint-report.json || true
+          npx eslint '{src,apps,libs,test}/**/*.ts' . --format json --output-file eslint-report.json || echo '[]' > eslint-report.json
 
       - name: Upload ESLint report
         uses: actions/upload-artifact@v4
@@ -64,9 +64,11 @@ jobs:
 
       - name: Fail if Linting Issues Found
         run: |
-          if grep -q '"severity":' eslint-report.json; then
+          if [ -s eslint-report.json ] && grep -q '"severity": 2' eslint-report.json; then
             echo "❌ ESLint errors found!"
             exit 1
+          else
+            echo "✅ No ESLint errors found."
           fi
 
   scan:
